### ISSUE TITLE
Generate image using image syntax?

### ISSUE THREAD

**Issue by zefhemel** [christ-offer/silverbullet-openai-plug#1]
Right now it just injects a URL (which you can click, of course), but it may be nicer to do something like:

```
Image of a friendly person
```

When you select this and run the `OpenAI: Image Generation` command it would replace it with

`![Image of a friendly person](URL HERE)`

**Comment by christ-offer** [comment]
Good call! I haven't even actually tested the image generation myself yet. I need to refill my OpenAI account hah. As with the other issue, I'll see if I can't get it sorted over the weekend!

**Comment by zefhemel** [comment]
Blind development, very YOLO 🤡

**Comment by christ-offer** [comment]
> Blind development, very YOLO 🤡

Haha, well code generation workes since its in beta, so more like One-Eyed Development. ;)

**Comment by christ-offer** [comment]
> Right now it just injects a URL (which you can click, of course), but it may be nicer to do something like:
> 
> ```
> Image of a friendly person
> ```
> 
> When you select this and run the `OpenAI: Image Generation` command it would replace it with
> 
> `![Image of a friendly person](URL HERE)`

Something like this? https://github.com/christ-offer/silverbullet-openai-plug/pull/3/files#diff-8b4685cee261a11a74c789bd8f44ea326340fcf9dbef1f28b94b99c1d166d249R120

**Comment by zefhemel** [comment]
Yep that looks like it could work. Did you test it? 😜

**Comment by christ-offer** [comment]
Hah, yes I did actually test it this time around.

**Comment by christ-offer** [comment]
closing this issue, added suggested fix here: https://github.com/christ-offer/silverbullet-openai-plug/pull/3

Will create a General Improvements issue to track suggestions and ideas for further improvements
