### ISSUE TITLE
Progress indication

### ISSUE THREAD

**Issue by zefhemel** [christ-offer/silverbullet-openai-plug#2]
Many of the commands take some time to complete, maybe add some `editor.flashNotification` messages to indicated something is happening?

**Comment by christ-offer** [comment]
Sounds like a good idea. It should probably check the settings page if "stream" is set to true, and not flash then, since stream gives, well, a stream. 

Also, note to self, check how the stream function works... 

I'll try to get it sorted over the weekend!

**Comment by zefhemel** [comment]
As an alternative to this, it may actually be nice if SB had an API to show a spinner of some sort, created an issue for this: https://github.com/silverbulletmd/silverbullet/issues/135

**Comment by christ-offer** [comment]
Added flasNotification here, closing this issue: https://github.com/christ-offer/silverbullet-openai-plug/pull/3

Will create a General Improvements issue to track suggestions and ideas.
